# @see [Article](https://githubnext.com/projects/repo-visualization/)
# @see [Repo](https://github.com/githubocto/repo-visualizer)
# @see [Action marketplace](https://github.com/marketplace/actions/repo-visualizer)
name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          root_path: "src/"
          output_file: ./media/diagram.svg
